CME_ERRORS = {
  '0': 'phone failure',
  '1': 'no connection to phone',
  '2': 'phone-adaptor link reserved',
  '3': 'operation not allowed',
  '4': 'operation not supported',
  '5': 'PH-SIM PIN required',
  '6': 'PH-FSIM PIN required',
  '7': 'PH-FSIM PUK required',
  '10': 'SIM not inserted',
  '11': 'SIM PIN required',
  '12': 'SIM PUK required',
  '13': 'SIM failure',
  '14': 'SIM busy',
  '15': 'SIM wrong',
  '16': 'incorrect password',
  '17': 'SIM PIN2 required',
  '18': 'SIM PUK2 required',
  '20': 'memory full',
  '21': 'invalid index',
  '22': 'not found',
  '23': 'memory failure',
  '24': 'text string too long',
  '25': 'invalid characters in text string',
  '26': 'dial string too long',
  '27': 'invalid characters in dial string',
  '30': 'no network service',
  '31': 'network timeout',
  '32': 'network not allowed - emergency call only',
}
