commands = { 'version':       'GSV',
             'battery':       'CBC',
             'temperature':   'CMTE?',
             'phonestatus':   'CPAS',
             'sleepmode':     'CSCLK?',
             'time':          'CCLK?',
             
             'volume':        'CLVL',
             'settime':       'CCLK',
             'ringerlevel':   'CRSL',
             'micgain':       'CMIC',
             'callerid':      'CLIP', 
             'localts':       'CLTS', 
             'ringtone':      'CALS',
             'leds':          'SLEDS',
             'smstype':       'CMGF',
             'sleeptype':     'CSCLK',

             'number':        'CNUM=?',
             'network':       'CREG?',
             'provider':      'COPS?',
             'providers':     'COPS=?',
             'signal' :       'CSQ',
             'imei':          'GSN',
             'imsi':          'CIMI',
             'bands':         'CBAND=?',
             'engineer':      'CENG=4',
             'cells':         'CENG?',
             'cellscan':      'CNETSCAN',
             'registration':  'CGREG?',

             'readsms':       'CMGR=1',
             'sendsms':       'CMGS=',
             'showsms':       'CMG="ALL"',
             
             'reset':         'CFUN=1,1',
            }
